"""Immutable data models for the Trading Decision Engine."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from decimal import Decimal
from enum import StrEnum
from typing import Any

from libraries.domain.trading.signals import SignalDirection, SignalStrength


class StrategyType(StrEnum):
    """Supported trading strategies."""

    SCALPING = "scalping"
    SWING = "swing"
    TREND_FOLLOWING = "trend_following"
    MEAN_REVERSION = "mean_reversion"
    BREAKOUT = "breakout"
    NEWS = "news"


class PositionSizingMethod(StrEnum):
    """Supported position sizing methods."""

    FIXED = "fixed"
    RISK_PERCENT = "risk_percent"
    ATR = "atr"
    KELLY = "kelly"
    VOLATILITY_BASED = "volatility_based"


@dataclass(frozen=True, slots=True)
class TradingSignal:
    """A single trading signal generated by the SignalGenerator."""

    direction: SignalDirection
    strength: SignalStrength
    strategy: StrategyType
    symbol: str
    confidence_score: float = 0.0  # 0-100
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class TradeSignal:
    """Raw trade signal from the signal generator before filtering."""

    direction: SignalDirection
    symbol: str
    entry_price: Decimal | None = None
    stop_loss: Decimal | None = None
    take_profit: Decimal | None = None
    confidence: float = 0.0
    strategy: StrategyType = StrategyType.SWING
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class SizingResult:
    """Result of position sizing calculation."""

    method: PositionSizingMethod
    units: Decimal
    notional_value: Decimal
    risk_amount: Decimal
    account_risk_pct: float
    max_units: Decimal | None = None
    metadata: dict[str, Any] = field(default_factory=dict)
