"""
Project ORION - Risk Management Engine (EPIC-007 Sprint-1).

Enterprise-grade Risk Management Engine that becomes the final approval
authority before any order reaches the Execution Engine.

NO trade should execute without passing every enabled risk policy.
"""

from __future__ import annotations

from libraries.domain.risk.context import RiskContext
from libraries.domain.risk.engine import RiskEngine, RiskEngineConfig
from libraries.domain.risk.evaluator import RiskEvaluator, RiskEvaluatorConfig
from libraries.domain.risk.exceptions import (
    CooldownActiveError,
    EmergencyAlreadyActiveError,
    EmergencyModeError,
    EngineError,
    EngineNotReadyError,
    EngineShutdownError,
    PolicyConfigurationError,
    PolicyError,
    PolicyExecutionError,
    PolicyNotFoundError,
    PolicyRegistrationError,
    ProfileError,
    ProfileNotFoundError,
    ProfileValidationError,
    RegistryError,
    RegistryFullError,
    RiskError,
    StatisticsError,
    TradingLockedError,
)
from libraries.domain.risk.interfaces import (
    AccountDataPort,
    BrokerHealthPort,
    EmergencyHandlerPort,
    MarketDataPort,
    MarketIntelligencePort,
    PortfolioDataPort,
    RiskEnginePort,
    RiskManagerPort,
    RiskPolicy,
    RiskProfilePort,
)
from libraries.domain.risk.manager import RiskManager, RiskManagerConfig
from libraries.domain.risk.models import (
    AccountProtectionLevel,
    AccountProtectionStatus,
    DrawdownMetrics,
    EmergencyModeStatus,
    EmergencyTrigger,
    PolicyCategory,
    PolicyEvaluation,
    PolicyResult,
    PolicySeverity,
    PortfolioRisk,
    PositionRisk,
    RiskDecision,
    RiskProfileType,
    RiskResult,
    RiskScore,
)
from libraries.domain.risk.policy import (
    BaseRiskPolicy,
    BrokerHealthProtectionPolicy,
    CooldownTimerPolicy,
    EmergencyStopPolicy,
    HardStopPolicy,
    HolidayProtectionPolicy,
    LiquidityProtectionPolicy,
    MarginProtectionPolicy,
    MarketDataQualityProtectionPolicy,
    MaximumConsecutiveLossesPolicy,
    MaximumCurrencyExposurePolicy,
    MaximumDailyLossPolicy,
    MaximumDrawdownPolicy,
    MaximumExposurePolicy,
    MaximumLeveragePolicy,
    MaximumMonthlyLossPolicy,
    MaximumOpenPositionsPolicy,
    MaximumPositionSizePolicy,
    MaximumSymbolExposurePolicy,
    MaximumWeeklyLossPolicy,
    NewsProtectionPolicy,
    RecoveryModePolicy,
    SlippageProtectionPolicy,
    SoftStopPolicy,
    SpreadProtectionPolicy,
    TradingHoursProtectionPolicy,
    TradingLockPolicy,
    VolatilityProtectionPolicy,
    WeekendProtectionPolicy,
    create_default_policies,
)
from libraries.domain.risk.profile import (
    RiskProfileConfig,
    RiskProfileManager,
)
from libraries.domain.risk.registry import RiskPolicyRegistry
from libraries.domain.risk.statistics import RiskStatistics, RiskStatsSnapshot
from libraries.domain.risk.validator import RiskValidator, ValidationReport

__all__ = [
    "AccountDataPort",
    "AccountProtectionLevel",
    "AccountProtectionStatus",
    # Base Policy
    "BaseRiskPolicy",
    "BrokerHealthPort",
    "BrokerHealthProtectionPolicy",
    "CooldownActiveError",
    "CooldownTimerPolicy",
    "DrawdownMetrics",
    "EmergencyAlreadyActiveError",
    "EmergencyHandlerPort",
    "EmergencyModeError",
    "EmergencyModeStatus",
    "EmergencyStopPolicy",
    "EmergencyTrigger",
    "EngineError",
    "EngineNotReadyError",
    "EngineShutdownError",
    "HardStopPolicy",
    "HolidayProtectionPolicy",
    "LiquidityProtectionPolicy",
    "MarginProtectionPolicy",
    "MarketDataPort",
    "MarketDataQualityProtectionPolicy",
    "MarketIntelligencePort",
    "MaximumConsecutiveLossesPolicy",
    "MaximumCurrencyExposurePolicy",
    "MaximumDailyLossPolicy",
    "MaximumDrawdownPolicy",
    "MaximumExposurePolicy",
    "MaximumLeveragePolicy",
    "MaximumMonthlyLossPolicy",
    "MaximumOpenPositionsPolicy",
    # Policies
    "MaximumPositionSizePolicy",
    "MaximumSymbolExposurePolicy",
    "MaximumWeeklyLossPolicy",
    "NewsProtectionPolicy",
    "PolicyCategory",
    "PolicyConfigurationError",
    "PolicyError",
    "PolicyEvaluation",
    "PolicyExecutionError",
    "PolicyNotFoundError",
    "PolicyRegistrationError",
    "PolicyResult",
    "PolicySeverity",
    "PortfolioDataPort",
    "PortfolioRisk",
    "PositionRisk",
    "ProfileError",
    "ProfileNotFoundError",
    "ProfileValidationError",
    "RecoveryModePolicy",
    "RegistryError",
    "RegistryFullError",
    "RiskContext",
    # Models
    "RiskDecision",
    # Core
    "RiskEngine",
    "RiskEngineConfig",
    # Interfaces
    "RiskEnginePort",
    # Exceptions
    "RiskError",
    "RiskEvaluator",
    "RiskEvaluatorConfig",
    "RiskManager",
    "RiskManagerConfig",
    "RiskManagerPort",
    "RiskPolicy",
    "RiskPolicyRegistry",
    "RiskProfileConfig",
    "RiskProfileManager",
    "RiskProfilePort",
    "RiskProfileType",
    "RiskResult",
    "RiskScore",
    "RiskStatistics",
    "RiskStatsSnapshot",
    "RiskValidator",
    "SlippageProtectionPolicy",
    "SoftStopPolicy",
    "SpreadProtectionPolicy",
    "StatisticsError",
    "TradingHoursProtectionPolicy",
    "TradingLockPolicy",
    "TradingLockedError",
    "ValidationReport",
    "VolatilityProtectionPolicy",
    "WeekendProtectionPolicy",
    # Factory
    "create_default_policies",
]
