apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orion-data
  namespace: orion
  labels:
    app.kubernetes.io/name: orion
    app.kubernetes.io/component: pvc
    app.kubernetes.io/part-of: orion
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3
