apiVersion: v1
kind: ResourceQuota
metadata:
  name: orion-quota
  namespace: orion
  labels:
    app.kubernetes.io/name: orion
    app.kubernetes.io/component: resource-quota
    app.kubernetes.io/part-of: orion
spec:
  hard:
    requests.cpu: "8"
    requests.memory: "16Gi"
    limits.cpu: "16"
    limits.memory: "32Gi"
    persistentvolumeclaims: "5"
    pods: "50"
    services: "10"
    configmaps: "20"
    secrets: "20"
    count/ingresses.networking.k8s.io: "2"
    count/networkpolicies.networking.k8s.io: "10"
