apiVersion: v1
kind: ServiceAccount
metadata:
  name: orion
  namespace: orion
  labels:
    app.kubernetes.io/name: orion
    app.kubernetes.io/component: service-account
    app.kubernetes.io/part-of: orion
automountServiceAccountToken: true
