apiVersion: v1
kind: Service
metadata:
  name: orion-api
  namespace: orion
  labels:
    app.kubernetes.io/name: orion
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: orion
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: orion
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
