apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orion-dev

namePrefix: dev-

commonLabels:
  environment: development

bases:
  - ../../base

patchesStrategicMerge:
  - replica_count.yaml

configMapGenerator:
  - name: orion-config
    behavior: merge
    literals:
      - ORION_ENVIRONMENT=development
      - ORION_LOG_LEVEL=debug

images:
  - name: orion/api
    newTag: dev-latest
  - name: orion/worker
    newTag: dev-latest
  - name: orion/scheduler
    newTag: dev-latest
