"""Immutable data models for the Strategy Abstraction Layer.

Defines broker-agnostic representations of trading signals, orders,
positions, trades, and strategy definitions.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from decimal import Decimal
from enum import StrEnum
from typing import Any


class SignalDirection(StrEnum):
    """Direction of a trading signal."""

    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    EXIT_LONG = "exit_long"
    EXIT_SHORT = "exit_short"


class SignalStrength(StrEnum):
    """Strength or conviction level of a signal."""

    STRONG = "strong"
    MODERATE = "moderate"
    WEAK = "weak"


class OrderType(StrEnum):
    """Supported order types."""

    MARKET = "market"
    LIMIT = "limit"
    STOP = "stop"
    STOP_LIMIT = "stop_limit"
    TRAILING_STOP = "trailing_stop"


class PositionSide(StrEnum):
    """Side of an open position."""

    LONG = "long"
    SHORT = "short"


class TradeStatus(StrEnum):
    """Lifecycle status of a trade."""

    PENDING = "pending"
    OPEN = "open"
    CLOSED = "closed"
    CANCELLED = "cancelled"
    REJECTED = "rejected"


class StrategyType(StrEnum):
    """Classification of strategy type."""

    TREND_FOLLOWING = "trend_following"
    MEAN_REVERSION = "mean_reversion"
    BREAKOUT = "breakout"
    GRID = "grid"
    ARBITRAGE = "arbitrage"
    MARKET_MAKING = "market_making"
    MOMENTUM = "momentum"
    STATISTICAL_ARBITRAGE = "statistical_arbitrage"
    MACHINE_LEARNING = "machine_learning"
    CUSTOM = "custom"


class StrategyStatus(StrEnum):
    """Lifecycle status of a strategy."""

    DRAFT = "draft"
    ACTIVE = "active"
    PAUSED = "paused"
    STOPPED = "stopped"
    ARCHIVED = "archived"
    FAILED = "failed"


@dataclass(frozen=True, slots=True)
class Signal:
    """A trading signal generated by a strategy."""

    strategy_id: str
    symbol: str
    direction: SignalDirection
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    strength: SignalStrength = SignalStrength.MODERATE
    price: Decimal | None = None
    confidence: float = 0.0
    reason: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class OrderRequest:
    """A request to place an order generated by a strategy."""

    strategy_id: str
    symbol: str
    order_type: OrderType
    side: str  # buy / sell
    quantity: Decimal
    price: Decimal | None = None
    stop_price: Decimal | None = None
    time_in_force: str = "gtc"
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    signal_id: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class Position:
    """An open position in the portfolio."""

    position_id: str
    strategy_id: str
    symbol: str
    side: PositionSide
    quantity: Decimal
    entry_price: Decimal
    current_price: Decimal
    unrealized_pnl: Decimal = Decimal("0")
    realized_pnl: Decimal = Decimal("0")
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class Trade:
    """A completed trade (execution result)."""

    trade_id: str
    strategy_id: str
    symbol: str
    side: str
    quantity: Decimal
    price: Decimal
    commission: Decimal = Decimal("0")
    swap: Decimal = Decimal("0")
    profit: Decimal = Decimal("0")
    status: TradeStatus = TradeStatus.CLOSED
    open_time: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    close_time: datetime | None = None
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class AssetAllocation:
    """Allocation of capital to a specific asset."""

    symbol: str
    weight: Decimal
    target_quantity: Decimal | None = None
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class BacktestResult:
    """Aggregated result of a strategy backtest."""

    strategy_id: str
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    total_return: Decimal = Decimal("0")
    sharpe_ratio: float = 0.0
    max_drawdown: Decimal = Decimal("0")
    win_rate: float = 0.0
    profit_factor: float = 0.0
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class StrategyMetadata:
    """Metadata describing a strategy's identity and configuration."""

    strategy_id: str
    name: str
    strategy_type: StrategyType = StrategyType.CUSTOM
    description: str = ""
    version: str = "1.0.0"
    author: str = ""
    tags: list[str] = field(default_factory=list)


@dataclass(frozen=True, slots=True)
class StrategyDefinition:
    """Full definition of a strategy including metadata and parameters."""

    metadata: StrategyMetadata
    status: StrategyStatus = StrategyStatus.DRAFT
    parameters: dict[str, Any] = field(default_factory=dict)
    symbols: list[str] = field(default_factory=list)
    allocation: AssetAllocation | None = None
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
