{{- if .Values.mesh.enabled }}
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: {{ include "orion.fullname" . }}-jwt
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orion.labels" . | nindent 4 }}
    app.kubernetes.io/component: mesh-security
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: api
  jwtRules:
    - issuer: {{ .Values.mesh.security.jwt.issuer | quote }}
      jwksUri: {{ .Values.mesh.security.jwt.jwksUri | default "https://auth.orion.example.com/.well-known/jwks.json" | quote }}
      forwardOriginalToken: {{ .Values.mesh.security.jwt.forwardOriginalToken | default true | quote }}
{{- end -}}
