{{- if .Values.worker.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "orion.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orion.labels" . | nindent 4 }}
    app.kubernetes.io/component: pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.worker.persistence.size }}
  storageClassName: {{ .Values.worker.persistence.storageClass }}
{{- end }}
